name: Faliactyl
defaulttheme: default
version: 2.1.2
website:
  port: 8080
  secret: Example Secret

discordserver:
  enabled: true
  invitelink: https://discord.gg/example

ads:
  enabled: false
  script: ''

guildblacklist:
  guilds:
  - ServerID
  - ServerID

pterodactyl:
  domain: https://panel.example.com
  key: EXAMPLE API KEY

AFK Party: 
  enabled: true
  webhook: https://discord.com/api/webhooks/example/example
  users: 25
  multiplier: 2	

linkvertise:
  enabled: true
  userid: 000000
  coins: 25

status:
  enabled: false
  script: https://example.com

stripe:
  enabled: false  
  key: 0000000000 # Replace this with your Stripe API Key
  coins: 200 # Coins per amount in USD
  amount: 1

smtp:
  enabled: false
  host: Example Host
  port: 7080
  username: Example Username
  password: Example Password

api:
  server:
    enabled: true
    key: API KEY
  client:
    j4r: 
      enabled: true
      ads:
      - name: Example Server 1
        id: 933803406513012807
        invite: https://discord.gg/7m5d4K8Mwg
        coins: 50
      - name: Example Server 2
        id: 933803406513012807
        invite: https://discord.gg/7m5d4K8Mwg
        coins: 50

    Role Packages:
      enabled: false
      Server: SERVERID # Replace SERVERID with your Guild/Server ID
      list: # Replace ROLEID with the Role ID, you can add as many as you want.
        RoleID: Package Name 

    bot:
      token: EXAMPLE BOT TOKEN
      joinguild:
        enabled: false
        guildid:
        - SERVERID
        - SERVERID
        forcejoin: false
        registeredrole: ""

    webhook:
      webhook_url: https://discord.com/api/webhooks/example/example
      auditlogs:
        enabled: true
        disabled: []

    passwordgenerator:
      signup: true # Use this to disable signups
      length: 8

    allow:
      gift: true
      newusers: true
      regen: true
      server:
        create: true
        modify: true
        delete: true

      overresourcessuspend: false # Enable this to suspend the server if the user edits the server resources
      renewsuspendsystem:
        enabled: false
        time: 3600
        cost: 0

    oauth2:
      id: "EXAMPLE OAUTH2 ID"
      secret: "EXAMPLE OAUTH2 SECRET"
      link: "http://dash.example.com"
      callbackpath: "/callback"
      prompt: true

      ip:
        trust x-forwarded-for: true
        block: []
        duplicate check: false

    packages:
      default: default
      list:
        default:
          ram: 1024
          disk: 1024
          cpu: 100
          servers: 1
          databases: 2
          allocations: 2
          backups: 2

    locations:
      '1':
        name: Example Location 1
        package: null
      '2':
        name: Example Location 2
        package: null

    eggs:
      paper:
        display: Minecraft Java
        minimum:
          ram: 1024
          disk: 1024
          cpu: 100
        maximum:
          ram: 2000
          disk: 2000
          cpu: 2000
        info:
          egg: 3
          docker_image: ghcr.io/pterodactyl/yolks:java_17
          startup: java -Xms128M -Xmx{{SERVER_MEMORY}}M -Dterminal.jline=false -Dterminal.ansi=true
            -jar {{SERVER_JARFILE}}
          environment:
            SERVER_JARFILE: server.jar
            BUILD_NUMBER: latest
          feature_limits:
            databases: 4
            backups: 4

    coins:
      enabled: true
      store:
        enabled: true
        ram:
          cost: 100
          per: 1
        disk:
          cost: 100
          per: 1
        cpu:
          cost: 100
          per: 1
        servers:
          cost: 100
          per: 1
        databases:
          cost: 100
          per: 1
        ports:
          cost: 100
          per: 1
        backups:
          cost: 100
          per: 1

  minero:
    enabled: false
    key: Minero Public Key

  arcio:
    enabled: false
    widgetid: Example WidgetID
    afk page:
      enabled: true
      path: afkwspath
      every: 10
      coins: 1

widget:
  enabled: false
  server_id: GUILD_ID
  channel_Id: CHANNEL_ID